name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  phpunit:
    strategy:
      matrix:
        php: [8.3, 8.2, 8.1]
        laravel: ['10.*', '11.*', '12.*', '13.*']
        os: [ubuntu-latest, windows-latest]
        exclude:
          - laravel: 12.*
            php: 8.1
          - laravel: 11.*
            php: 8.1
          - laravel: 13.*
            php: 8.2
          - laravel: 13.*
            php: 8.1
      fail-fast: false

    runs-on: ${{ matrix.os }}

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: fileinfo

      - name: Install dependencies
        run: |
          # Install Laravel version per matrix
          composer require --dev "laravel/framework:${{ matrix.laravel }}" --no-interaction

          composer install --no-interaction

      - name: Execute PHPUnit tests
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/logs/clover.xml
